DATABASE_URL="postgresql://neondb_owner:npg_Nqe1IGxJFUL2@ep-shy-union-a1rk3344-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
ETL_EMAIL_USER="schetankumar123@gmail.com"
ETL_EMAIL_PASSWORD="bjmhumpawufghenv"